var annotated_dup =
[
    [ "re_3_data_t", "structre__3__data__t.html", "structre__3__data__t" ],
    [ "re_5_data_t", "structre__5__data__t.html", "structre__5__data__t" ],
    [ "re_6_data_t", "structre__6__data__t.html", "structre__6__data__t" ],
    [ "re_6_flags_t", "structre__6__flags__t.html", "structre__6__flags__t" ],
    [ "re_6_mac_addr_24_t", "structre__6__mac__addr__24__t.html", "structre__6__mac__addr__24__t" ],
    [ "re_7_data_t", "structre__7__data__t.html", "structre__7__data__t" ],
    [ "re_8_data_t", "structre__8__data__t.html", "structre__8__data__t" ],
    [ "re_c5_data_t", "structre__c5__data__t.html", "structre__c5__data__t" ],
    [ "re_ca_uart_ble_ack_t", "structre__ca__uart__ble__ack__t.html", "structre__ca__uart__ble__ack__t" ],
    [ "re_ca_uart_ble_adv_t", "structre__ca__uart__ble__adv__t.html", "structre__ca__uart__ble__adv__t" ],
    [ "re_ca_uart_ble_all_bools_t", "structre__ca__uart__ble__all__bools__t.html", "structre__ca__uart__ble__all__bools__t" ],
    [ "re_ca_uart_ble_all_t", "structre__ca__uart__ble__all__t.html", "structre__ca__uart__ble__all__t" ],
    [ "re_ca_uart_ble_bool_t", "structre__ca__uart__ble__bool__t.html", "structre__ca__uart__ble__bool__t" ],
    [ "re_ca_uart_ble_fltr_id_t", "structre__ca__uart__ble__fltr__id__t.html", "structre__ca__uart__ble__fltr__id__t" ],
    [ "re_ca_uart_ble_id_t", "structre__ca__uart__ble__id__t.html", "structre__ca__uart__ble__id__t" ],
    [ "re_ca_uart_led_ctrl_t", "structre__ca__uart__led__ctrl__t.html", "structre__ca__uart__led__ctrl__t" ],
    [ "re_ca_uart_miso_payload_buf_encoded_ack_t", "structre__ca__uart__miso__payload__buf__encoded__ack__t.html", "structre__ca__uart__miso__payload__buf__encoded__ack__t" ],
    [ "re_ca_uart_miso_payload_buf_encoded_device_id_t", "structre__ca__uart__miso__payload__buf__encoded__device__id__t.html", "structre__ca__uart__miso__payload__buf__encoded__device__id__t" ],
    [ "re_ca_uart_miso_payload_buf_encoded_get_all_params_t", "structre__ca__uart__miso__payload__buf__encoded__get__all__params__t.html", "structre__ca__uart__miso__payload__buf__encoded__get__all__params__t" ],
    [ "re_ca_uart_mosi_payload_buf_encoded_all_params_t", "structre__ca__uart__mosi__payload__buf__encoded__all__params__t.html", "structre__ca__uart__mosi__payload__buf__encoded__all__params__t" ],
    [ "re_ca_uart_mosi_payload_buf_encoded_bool_t", "structre__ca__uart__mosi__payload__buf__encoded__bool__t.html", "structre__ca__uart__mosi__payload__buf__encoded__bool__t" ],
    [ "re_ca_uart_mosi_payload_buf_encoded_get_device_id_t", "structre__ca__uart__mosi__payload__buf__encoded__get__device__id__t.html", "structre__ca__uart__mosi__payload__buf__encoded__get__device__id__t" ],
    [ "re_ca_uart_mosi_payload_buf_encoded_led_ctrl_t", "structre__ca__uart__mosi__payload__buf__encoded__led__ctrl__t.html", "structre__ca__uart__mosi__payload__buf__encoded__led__ctrl__t" ],
    [ "re_ca_uart_mosi_payload_buf_encoded_set_fltr_id_t", "structre__ca__uart__mosi__payload__buf__encoded__set__fltr__id__t.html", "structre__ca__uart__mosi__payload__buf__encoded__set__fltr__id__t" ],
    [ "re_ca_uart_payload_t", "structre__ca__uart__payload__t.html", "structre__ca__uart__payload__t" ],
    [ "re_e0_data_t", "structre__e0__data__t.html", "structre__e0__data__t" ],
    [ "re_e1_data_t", "structre__e1__data__t.html", "structre__e1__data__t" ],
    [ "re_e1_flags_t", "structre__e1__flags__t.html", "structre__e1__flags__t" ],
    [ "re_f0_data_t", "structre__f0__data__t.html", "structre__f0__data__t" ],
    [ "re_fa_data_t", "structre__fa__data__t.html", "structre__fa__data__t" ],
    [ "re_i16_coeffs_t", "structre__i16__coeffs__t.html", "structre__i16__coeffs__t" ],
    [ "re_ibeacon_data_t", "structre__ibeacon__data__t.html", "structre__ibeacon__data__t" ],
    [ "re_u16_coeffs_t", "structre__u16__coeffs__t.html", "structre__u16__coeffs__t" ],
    [ "re_u9_coeffs_t", "structre__u9__coeffs__t.html", "structre__u9__coeffs__t" ]
];